language: node_js
node_js:
  - "7"
cache:
  directories:
    - node_modules
    - bower_components
script:
  - npm install -g knex bower
  - bower install
  - knex migrate:latest
  - npm test
  - .travis/deploy.sh
after_success:
  - .travis/notify.sh "1"
after_failure:
  - .travis/notify.sh "0"
